export function getTimes() {
  let list = [{
      timeList: '06:00~06:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '06:30~07:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '07:00~07:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '07:30~08:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '08:00~08:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '08:30~09:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '09:00~09:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '09:30~10:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '10:00~10:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '10:30~11:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '11:00~11:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '11:30~12:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '12:00~12:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '12:30~13:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '13:00~13:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '13:30~14:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '14:00~14:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '14:30~15:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '15:00~15:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '15:30~16:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '16:00~16:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '16:30~17:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '17:00~17:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '17:30~18:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '18:00~18:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '18:30~19:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '19:00~19:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '19:30~20:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '20:00~20:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '20:30~21:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '21:00~21:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '21:30~22:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '22:00~22:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '22:30~23:00',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '23:00~23:30',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    },
    {
      timeList: '23:30~23:59',
      imageSource: '/images/order/white.png',
      imageType: 0,
      company: '',
    }
  ];
  return list;
}